# Use the specific base image
FROM mcr.microsoft.com/devcontainers/python:3.11

# Install OS-level packages

# Update the package list
# RUN apt-get update

# Remember to use `-y` to avoid prompts asking for confirmation during the build
# RUN apt-get install -y .....