version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"